// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSV5rDl4n4w_iWxX7ngRDwhfnpHmIjxow',
    appId: '1:745640720189:web:68f2e40f34920aa766b754',
    messagingSenderId: '745640720189',
    projectId: 'flutter-firebase-project-b0708',
    authDomain: 'flutter-firebase-project-b0708.firebaseapp.com',
    storageBucket: 'flutter-firebase-project-b0708.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADwypdSzR5c9ydl3kdxMVBDa368rxuHuY',
    appId: '1:745640720189:android:ed357a34010f9fab66b754',
    messagingSenderId: '745640720189',
    projectId: 'flutter-firebase-project-b0708',
    storageBucket: 'flutter-firebase-project-b0708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiRnrt5PwDq_osGiy7-jERjb5y48cst4k',
    appId: '1:745640720189:ios:d9234910570ad17966b754',
    messagingSenderId: '745640720189',
    projectId: 'flutter-firebase-project-b0708',
    storageBucket: 'flutter-firebase-project-b0708.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiRnrt5PwDq_osGiy7-jERjb5y48cst4k',
    appId: '1:745640720189:ios:d9234910570ad17966b754',
    messagingSenderId: '745640720189',
    projectId: 'flutter-firebase-project-b0708',
    storageBucket: 'flutter-firebase-project-b0708.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSV5rDl4n4w_iWxX7ngRDwhfnpHmIjxow',
    appId: '1:745640720189:web:f2a1f86fa6a42ae766b754',
    messagingSenderId: '745640720189',
    projectId: 'flutter-firebase-project-b0708',
    authDomain: 'flutter-firebase-project-b0708.firebaseapp.com',
    storageBucket: 'flutter-firebase-project-b0708.appspot.com',
  );
}
